apiVersion: v1
kind: ReplicationController
metadata:
  name: khagesh-rc
spec:
  replicas: 3
  selector:
    app: khageshapp
  template:
    metadata:
      labels:
        app: khageshapp
    spec:
      containers:
        - name: khagesh-java-container
          image: khagesh/khageshapp:1
          ports:
            - containerPort: 8080
